apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql-deployment
  labels:
    app: sql-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sql-server
  template:
    metadata:
      labels:
        app: sql-server
    spec:
      containers:
      - name: sql-server
        image: 
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value:"Y"
        - name: MSSQL_SA_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql
              key: pw
        volumeMounts:
        - name: sql-server-data
          mountPath: /var/opt/mysql
      volumes:
      - name: sql-server-data
        persistentVolumeClaim:
          claimName: sql-server-pvc

